export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const POST_DATA_REQUEST = 'POST_DATA_REQUEST';
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS';
export const POST_DATA_FAILURE = 'POST_DATA_FAILURE';

export const GET_CART_DATA_REQUEST = 'GET_CART_DATA_REQUEST';
export const GET_CART_DATA_SUCCESS = 'GET_CART_DATA_SUCCESS';
export const GET_CART_DATA_FAILURE = 'GET_CART_DATA_FAILURE';

// DRESSES


export const GET_WEDDING_DATA_REQUEST = 'GET_WEDDING_DATA_REQUEST';
export const GET_WEDDING_DATA_SUCCESS = 'GET_WEDDING_DATA_SUCCESS';
export const GET_WEDDING_DATA_FAILURE = 'GET_WEDDING_DATA_FAILURE';

export const GET_CASUAL_DATA_REQUEST = 'GET_CASUAL_DATA_REQUEST';
export const GET_CASUAL_DATA_SUCCESS = 'GET_CASUAL_DATA_SUCCESS';
export const GET_CASUAL_DATA_FAILURE = 'GET_CASUAL_DATA_FAILURE';

export const GET_FORMAL_DATA_REQUEST = 'GET_FORMAL_DATA_REQUEST';
export const GET_FORMAL_DATA_SUCCESS = 'GET_FORMAL_DATA_SUCCESS';
export const GET_FORMAL_DATA_FAILURE = 'GET_FORMAL_DATA_FAILURE';

export const GET_PARTY_DATA_REQUEST = 'GET_PARTY_DATA_REQUEST';
export const GET_PARTY_DATA_SUCCESS = 'GET_PARTY_DATA_SUCCESS';
export const GET_PARTY_DATA_FAILURE = 'GET_PARTY_DATA_FAILURE';

export const GET_WHITE_DATA_REQUEST = 'GET_WHITE_DATA_REQUEST';
export const GET_WHITE_DATA_SUCCESS = 'GET_WHITE_DATA_SUCCESS';
export const GET_WHITE_DATA_FAILURE = 'GET_WHITE_DATA_FAILURE';


export const GET_BLACK_DATA_REQUEST = 'GET_BLACK_DATA_REQUEST';
export const GET_BLACK_DATA_SUCCESS = 'GET_BLACK_DATA_SUCCESS';
export const GET_BLACK_DATA_FAILURE = 'GET_BLACK_DATA_FAILURE';


// paints
export const GET_WORKPAINT_DATA_REQUEST = 'GET_WORKPAINT_DATA_REQUEST';
export const GET_WORKPAINT_DATA_SUCCESS = 'GET_WORKPAINT_DATA_SUCCESS';
export const GET_WORKPAINT_DATA_FAILURE = 'GET_WORKPAINT_DATA_FAILURE';

export const GET_PAINT_DATA_REQUEST = 'GET_PAINT_DATA_REQUEST';
export const GET_PAINT_DATA_SUCCESS = 'GET_PAINT_DATA_SUCCESS';
export const GET_PAINT_DATA_FAILURE = 'GET_PAINT_DATA_FAILURE';
// JEANS

export const GET_BOOTCUT_DATA_REQUEST = 'GET_BOOTCUT_DATA_REQUEST';
export const GET_BOOTCUT_DATA_SUCCESS = 'GET_BOOTCUT_DATA_SUCCESS';
export const GET_BOOTCUT_DATA_FAILURE = 'GET_BOOTCUT_DATA_FAILURE';


export const GET_BOYFRIEND_DATA_REQUEST = 'GET_BOYFRIEND_DATA_REQUEST';
export const GET_BOYFRIEND_DATA_SUCCESS = 'GET_BOYFRIEND_DATA_SUCCESS';
export const GET_BOYFRIEND_DATA_FAILURE = 'GET_BOYFRIEND_DATA_FAILURE';



export const GET_FLARE_DATA_REQUEST = 'GET_FLARE_DATA_REQUEST';
export const GET_FLARE_DATA_SUCCESS = 'GET_FLARE_DATA_SUCCESS';
export const GET_FLARE_DATA_FAILURE = 'GET_FLARE_DATA_FAILURE';


export const GET_SKINNY_DATA_REQUEST = 'GET_SKINNY_DATA_REQUEST';
export const GET_SKINNY_DATA_SUCCESS = 'GET_SKINNY_DATA_SUCCESS';
export const GET_SKINNY_DATA_FAILURE = 'GET_SKINNY_DATA_FAILURE';


export const GET_STRAIGHT_DATA_REQUEST = 'GET_STRAIGHT_DATA_REQUEST';
export const GET_STRAIGHT_DATA_SUCCESS = 'GET_STRAIGHT_DATA_SUCCESS';
export const GET_STRAIGHT_DATA_FAILURE = 'GET_STRAIGHT_DATA_FAILURE';


export const GET_WIDELEG_DATA_REQUEST = 'GET_WIDELEG_DATA_REQUEST';
export const GET_WIDELEG_DATA_SUCCESS = 'GET_WIDELEG_DATA_SUCCESS';
export const GET_WIDELEG_DATA_FAILURE = 'GET_WIDELEG_DATA_FAILURE';

// SHOES


export const GET_BIRKENSTOCK_DATA_FAILURE = 'GET_BIRKENSTOCK_DATA_FAILURE';
export const GET_BIRKENSTOCK_DATA_REQUEST = 'GET_BIRKENSTOCK_DATA_REQUEST';
export const GET_BIRKENSTOCK_DATA_SUCCESS = 'GET_BIRKENSTOCK_DATA_SUCCESS';


export const GET_EMBLESHED_DATA_REQUEST = 'GET_EMBLESHED_DATA_REQUEST';
export const GET_EMBLESHED_DATA_SUCCESS = 'GET_EMBLESHED_DATA_SUCCESS';
export const GET_EMBLESHED_DATA_FAILURE = 'GET_EMBLESHED_DATA_FAILURE';


export const GET_SNEAKER_DATA_SUCCESS = 'GET_SNEAKER_DATA_SUCCESS';
export const GET_SNEAKER_DATA_FAILURE = 'GET_SNEAKER_DATA_FAILURE';
export const GET_SNEAKER_DATA_REQUEST = 'GET_SNEAKER_DATA_REQUEST';


// filter
export const FILTER_DATA = "FILTER_DATA";
// single page

export const SINGLE_PAGE_DATA = "SINGLE_PAGE_DATA";