const GET_REQUEST = "GET_REQUEST";
const GET_SUCCESS = "GET_SUCCESS";
const GET_FAILURE = "GET_FAILURE";

const POST_REQUEST = "POST_REQUEST";
const POST_SUCCESS = "POST_SUCCESS";
const POST_FAILURE = "POST_FAILURE";
const TOGGLE = "TOGGLE"


export {GET_FAILURE, GET_REQUEST, GET_SUCCESS, POST_FAILURE, POST_REQUEST, POST_SUCCESS, TOGGLE};