export const countryAndCode = [
    { id: 1, name: 'Afghanistan', code: 93 },
    { id: 2, name: 'Albania', code: 355 },
    { id: 3, name: 'Algeria', code: 213 },
    { id: 4, name: 'Andorra', code: 376 },
    { id: 5, name: 'Angola', code: 1 },
    { id: 6, name: 'Australia', code: 61 },
    { id: 7, name: 'Argentina', code: 54 },
    { id: 8, name: 'Austria', code: 43 },
    { id: 9, name: 'Bahrain', code: 973 },
    { id: 10, name: 'Bangladesh', code: 880 },
    { id: 11, name: 'Belarus', code: 375 },
    { id: 12, name: 'Belgium', code: 32 },
    { id: 13, name: 'Bhutan', code: 975 },
    { id: 14, name: 'China', code: 86 },
    { id: 15, name: 'Cocos Islands', code: 61 },
    { id: 16, name: 'Colombia', code: 57 },
    { id: 17, name: 'Denmark', code: 45 },
    { id: 18, name: 'Egypt', code: 20 },
    { id: 19, name: 'Eritrea', code: 291 },
    { id: 20, name: 'Faroe Islands', code: 298 },
    { id: 21, name: 'Finland', code: 358 },
    { id: 22, name: 'France', code: 33 },
    { id: 23, name: 'Gambia', code: 220 },
    { id: 24, name: 'Georgia', code: 995 },
    { id: 25, name: 'Germany', code: 49 },
    { id: 26, name: 'Greenland', code: 299 },
    { id: 27, name: 'Guatemala', code: 502 },
    { id: 28, name: 'Hong Kong', code: 852 },
    { id: 29, name: 'Iceland', code: 354 },
    { id: 30, name: 'India', code: 91 },
    { id: 31, name: 'Indonesia', code: 62 },
    { id: 32, name: 'iran', code: 98 },
    { id: 33, name: 'iraq', code: 964 },
    { id: 34, name: 'Ireland', code: 353 },
    { id: 35, name: 'Israel', code: 972 },
    { id: 36, name: 'Italy', code: 39 },
    { id: 37, name: 'Japan', code: 81 },
    { id: 38, name: 'Japan', code: 962 },
    { id: 39, name: 'Kazakhstan', code: 7 },
    { id: 40, name: 'Kuwait', code: 965 },
    { id: 41, name: 'Libya', code: 218 },
    { id: 42, name: 'Liberia', code: 231 },
    { id: 43, name: 'Macau', code: 853 },
    { id: 44, name: 'Macedonia', code: 389 },
    { id: 45, name: 'Malaysia', code: 60 },
    { id: 46, name: 'Maldives', code: 960 },
    { id: 47, name: 'Mexico', code: 52 },
    { id: 48, name: 'Monaco', code: 377 },
    { id: 49, name: 'Myanmar', code: 95 },
    { id: 50, name: 'Namibia', code: 264 },
    { id: 51, name: 'Nepal', code: 977 },
    { id: 52, name: 'Netherlands', code: 31 },
    { id: 53, name: 'Netherlands Antilles', code: 599 },
    { id: 54, name: 'New Zealand', code: 64 },
    { id: 55, name: 'Nigeria', code: 234 },
    { id: 56, name: 'North Korea', code: 850 },
    { id: 57, name: 'Norway', code: 47 },
    { id: 58, name: 'Oman', code: 968 },
    { id: 59, name: 'Pakistan', code: 92 },
    { id: 60, name: 'Palau', code: 680 },
    { id: 61, name: 'Palestine', code: 970 },
    { id: 62, name: 'Peru', code: 51 },
    { id: 63, name: 'Philippines', code: 63 },
    { id: 64, name: 'Poland', code: 48 },
    { id: 65, name: 'Portugal', code: 351 },
    { id: 66, name: 'Qatar', code: 974 },
    { id: 67, name: 'Romania', code: 40 },
    { id: 68, name: 'Russia', code: 7 },
    { id: 69, name: 'Saint Martin', code: 590 },
    { id: 70, name: 'Saudi Arabia', code: 966 },
    { id: 71, name: 'Singapore', code: 65 },
    { id: 72, name: 'South Africa', code: 27 },
    { id: 73, name: 'South Korea', code: 82 },
    { id: 74, name: 'Spain', code: 34 },
    { id: 75, name: 'Sri Lanka', code: 94 },
    { id: 76, name: 'Switzerland', code: 41 },
    { id: 77, name: 'Taiwan', code: 886 },
    { id: 78, name: 'Thailand', code: 66 },
    { id: 79, name: 'Turkey', code: 90 },
    { id: 80, name: 'Turkmenistan', code: 993 },
    { id: 81, name: 'Uganda', code: 256 },
    { id: 82, name: 'Ukraine', code: 380 },
    { id: 83, name: 'United Arab Emirates', code: 971 },
    { id: 84, name: 'United Kingdom', code: 44 },
    { id: 85, name: 'United States', code: 1 },
    { id: 86, name: 'Vietnam', code: 84 },
    { id: 87, name: 'Western Sahara', code: 212 },
    { id: 88, name: 'Yemen', code: 967 },
    { id: 89, name: 'Zambia', code: 260 },
    { id: 90, name: 'Zimbabwe', code: 263 },
];
